#!/bin/bash

#--------------------------------------------------------------------#
#
#       Set up pretty colors
#
#--------------------------------------------------------------------#

RED='\033[0;31m'
GREEN='\033[0;32m'
LIGHTBLUE='\033[0;34m'
NC='\033[0m' # No Color

DOTFILES_DIR="$HOME/.dotfiles"
DOTFILES_BACKUP_DIR="$HOME/.dotfiles_backup"

#--------------------------------------------------------------------#
#
#       Set up backup location

mkdir $DOTFILES_BACKUP_DIR $DOTFILES_BACKUP_DIR/bash $DOTFILES_BACKUP_DIR/git $DOTFILES_BACKUP_DIR/oh-my-zsh $DOTFILES_BACKUP_DIR/ssh $DOTFILES_BACKUP_DIR/sublime $DOTFILES_BACKUP_DIR/terminator $DOTFILES_BACKUP_DIR/wp-cli $DOTFILES_BACKUP_DIR/zsh
echo -e "${GREEN}Backup dir created.\n${NC}"

#--------------------------------------------------------------------#
#
#       Bash

if [[ -f "$HOME/.bashrc" ]]
then
	mv $HOME/.bashrc $DOTFILES_BACKUP_DIR/bash/.bashrc
fi
ln -s $DOTFILES_DIR/bash/bashrc ~/.bashrc
echo -e "${GREEN}Bash config symlinked\n${NC}"

#--------------------------------------------------------------------#
#
#       Git

ln -s ~/.dotfiles/git/gitconfig ~/.gitconfig
ln -s ~/.dotfiles/git/gitignore_global ~/.gitignore_global
echo -e "${GREEN}Git config symlinked\n${NC}"

#--------------------------------------------------------------------#
#
#       Sublime Text 3

# Setting dir is created at program launch
# so we will create settings dir if it doesn't exist

if [[ ! -d "$HOME/.config/sublime-text-3/Packages/User" ]]
then
	mkdir -pv "$HOME/.config/sublime-text-3/Packages/User"
fi

if [[ -f "$HOME/.config/sublime-text-3/Packages/User/Preferences.sublime-settings" ]]
then
	mv "$HOME/.config/sublime-text-3/Packages/User/Preferences.sublime-settings" "$DOTFILES_BACKUP_DIR/sublime/Preferences.sublime-settings"
fi
ln -s "$DOTFILES_DIR/sublime/Preferences.sublime-settings" "$HOME/.config/sublime-text-3/Packages/User/Preferences.sublime-settings"

if [[ -f "$HOME/.config/sublime-text-3/Packages/User/Package Control.sublime-settings" ]]
then
	mv "$HOME/.config/sublime-text-3/Packages/User/Package Control.sublime-settings" "$DOTFILES_BACKUP_DIR/sublime/Package Control.sublime-settings"
fi
ln -s "$DOTFILES_DIR/sublime/Package Control.sublime-settings" "$HOME/.config/sublime-text-3/Packages/User/Package Control.sublime-settings"

ln -s "$DOTFILES_DIR/sublime/Snippets" "$HOME/.config/sublime-text-3/Packages/User/Snippets"

echo -e "${GREEN}Sublime config symlinked\n${NC}"

#--------------------------------------------------------------------#
#
#       ZSH

if [[ -f "$HOME/.zshrc" ]]
then
	mv $HOME/.zshrc $DOTFILES_BACKUP_DIR/zsh/.zshrc
fi
	ln -s $DOTFILES_DIR/zsh/zshrc $HOME/.zshrc
echo -e "${GREEN}ZSH config symlinked\n${NC}"

#--------------------------------------------------------------------#
#
#       Oh My ZSH

ln -s ~/.dotfiles/oh-my-zsh/alias.zsh ~/.oh-my-zsh/custom/alias.zsh

#--------------------------------------------------------------------#
#
#       Terminator

mkdir ~/.config/terminator && ln -s ~/.dotfiles/terminator/config ~/.config/terminator/config
echo -e "${GREEN}Terminator config symlinked\n${NC}"

#--------------------------------------------------------------------#
#
# Make a noise!

echo -en "\007" 
echo -e "${GREEN}Symlinking done!\n${NC}"