export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

plugins=(git git-flow-completion nvm)

# User configuration

export PATH=$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# Toggle between full agnoster prompt and a short prompt
toggle_prompt() {
  if [[ "$ZSH_THEME" == "agnoster" ]]; then
    ZSH_THEME="minimal"
    source $ZSH/oh-my-zsh.sh
  else
    ZSH_THEME="agnoster"
    source $ZSH/oh-my-zsh.sh
  fi
}
alias tp='toggle_prompt'

# NVM Bash Completion
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/bain/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/bain/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/bain/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/bain/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.config/composer/vendor/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
